### ISSUE TITLE
cri使用cilium时，脚本执行出现bug

### ISSUE THREAD

**Issue by liyongcool** [lework/kainstall#10]
[[ "${KUBE_NETWORK:-}" == "cilium" ]] && check::kernel 4.9.17
传入func check::kernel后 version变量的值就变为4197，但操作系统kernel version为类似4.18.0-xxx时,就会校验不通过，但实际上，kernel version是够的

**Comment by lework** [comment]
感谢指出，现已修复。
https://github.com/lework/kainstall/blob/d1f188ccd5de367227ad6f1b0e6b6827e5cc0b06/kainstall-centos.sh#L1254-L1272
