### ISSUE TITLE
问一下，我只有一个主节点，使用kainstall工具搭建的k8s，基本什么都没装，重启后虚机崩掉，拼命重启是什么原因啊

### ISSUE THREAD

**Issue by linlongdeng** [lework/kainstall#16]
打开pod ，大量发现这个错误
 Failed to create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "local-path-provisioner-55d9494bdd-g4f7t": Error response from daemon: OCI runtime create failed

**Comment by lework** [comment]
这个看下 `docker` ，`containerd` 的服务状态。

**Comment by linlongdeng** [comment]
[root@k8s-master-node1 ~]# systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: active (running) since 五 2021-09-17 11:07:05 CST; 2min 54s ago
     Docs: https://docs.docker.com
 Main PID: 1591 (dockerd)
    Tasks: 107
   Memory: 191.8M
   CGroup: /system.slice/docker.service
           ├─ 1591 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
           ├─15006 set-ipv6 /var/run/docker/netns/d378d8fa35ee all false
           ├─15018 set-ipv6 /var/run/docker/netns/7ea1ccdad373 all false
           ├─15019 set-ipv6 /var/run/docker/netns/4626e6ac80e0 all false
           ├─15020 set-ipv6 /var/run/docker/netns/327ac5afba0e all false
           ├─15021 set-ipv6 /var/run/docker/netns/3a820ea65202 all false
           ├─15022 set-ipv6 /var/run/docker/netns/4616c60d3483 all false
           └─15024 set-ipv6 /var/run/docker/netns/b19c8841f8c5 all false

9月 17 11:07:04 k8s-master-node1 dockerd[1591]: time="2021-09-17T11:07:04.894243753+08:00" level=info msg="Removing stale sandbox 87e7ddcc3f934053550d6f3e8fd4c6d27ccaf8f41bf330a1b86942dd5c899f44 (e0e217fe1a1af7...0d9afd96bb72f1)"
9月 17 11:07:04 k8s-master-node1 dockerd[1591]: time="2021-09-17T11:07:04.895771605+08:00" level=warning msg="Error (Unable to complete atomic operation, key modified) deleting object [endpoint a9ea8ca6556786e1...], retrying...."
9月 17 11:07:05 k8s-master-node1 dockerd[1591]: time="2021-09-17T11:07:05.121366996+08:00" level=info msg="Removing stale sandbox 948155dcbeee58e37718b70fde0c3625452af46acd1fde702986c89a04a5ee4d (f31e728a851358...f4e5c4f28f2405)"
9月 17 11:07:05 k8s-master-node1 dockerd[1591]: time="2021-09-17T11:07:05.185168228+08:00" level=warning msg="Error (Unable to complete atomic operation, key modified) deleting object [endpoint 716ef100276056cb...], retrying..

**Comment by linlongdeng** [comment]
memory cgroup out of memory : kill process 17158(containerd-shim) socre 0 or sacrifice child

**Comment by linlongdeng** [comment]
系统CentOS Linux release 7.9.2009 (Core)，安装命令是 
 	 bash kainstall-centos.sh  \
  init \
  --master 192.168.133.180 \
  --user root \
  --password 123456 \
  --port 22 \
  --version 1.20.6
重启之后 ，100%出现，还什么都没装，只是改了编辑 kube-apiserver.yaml文件
vi /etc/kubernetes/manifests/kube-apiserver.yaml的- --service-node-port-range=1-65535

**Comment by linlongdeng** [comment]
[root@k8s-master-node1 ~]# systemctl status containerd 
● containerd.service - containerd container runtime
   Loaded: loaded (/usr/lib/systemd/system/containerd.service; enabled; vendor preset: disabled)
   Active: active (running) since 五 2021-09-17 11:06:57 CST; 13min ago
     Docs: https://containerd.io
  Process: 1089 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
 Main PID: 1099 (containerd)
    Tasks: 309
   Memory: 356.4M
   CGroup: /system.slice/containerd.service
           ├─ 1099 /usr/bin/containerd
           ├─11374 /usr/bin/containerd-shim-runc-v2 -namespace moby -id d5f6eccc8b21ca064e939ede4da447efa5cd259fd380841b3ce8ce546e561f8e -address /run/containerd/containerd.sock
           ├─11427 /usr/bin/containerd-shim-runc-v2 -namespace moby -id 0c98963db36d8b2f0a8fd15be516e8438d13eb36829fafa13aa2863da9745579 -address /run/containerd/containerd.sock
           ├─12104 /usr/bin/containerd-shim-runc-v2 -namespace moby -id 3174f67a4c65ef81527bd4312797897db84b32aecba6869989b3148f8a7b2213 -address /run/containerd/containerd.sock
           ├─12181 /usr/bin/containerd-shim-runc-v2 -namespace moby -id 021f1516937b6393e7b7b3704ea441811ed72262420bda3a55fcf5d615333840 -address /run/containerd/containerd.sock
           ├─12961 /usr/bin/containerd-shim-runc-v2 -namespace moby -id 79caaa440ecb7b9777b5cf8906c25eb82bdc0f756f7ffdc01e5baaa2fab32ac8 -address /run/containerd/containerd.sock
           ├─13011 /usr/bin/containerd-shim-runc-v2 -namespace moby -id e8a11c04c8e97478ca4add0ae362fd2a3ff552095e4a509fcadf0736857e182c -address /run/containerd/containerd.sock
           ├─13308 /usr/bin/containerd-shim-runc-v2 -namespace moby -id 7b09c4dffc219c6cf6ee5e50cf23f39f572d0cc73920214bdaba0cbd90eb4cc3 -address /run/containerd/containerd.sock
           ├─13378 /usr/bin/containerd-shim-runc-v2 -namespace moby -id 11c20323d5a78d2ec26b2c57f90705fed2a0ab37e653bd1ef98f5e932bf06f34 -address /run/containerd/containerd.sock
           ├─13519 /usr/bin/containerd-shim-runc-v2 -namespace moby -id 88ba50bce261665e6d58c6f2cd7c29dff58b419f5cf2e20dfff6576f14343187 -address /run/containerd/containerd.sock
           ├─13521 /usr/bin/containerd-shim-runc-v2 -namespace moby -id 71815007d52eec49b17c4b784b19928c7b7e5ac7a17b379d93bdad396731e2db -address /run/containerd/containerd.sock
           ├─13848 /usr/bin/containerd-shim-runc-v2 -namespace moby -id c5d2eb6d461387e1fee6ec487d32ec3fd33f1500e3957634f9a4fe010913deb9 -address /run/containerd/containerd.sock
           ├─59793 /usr/bin/containerd-shim-runc-v2 -namespace moby -id 96783026c24073e11355be3c4d2259066ae72912ba7367dfa204a9586e90fcf3 -address /run/containerd/containerd.sock
           ├─59803 runc --root /var/run/docker/runtime-runc/moby --log /run/containerd/io.containerd.runtime.v2.task/moby/96783026c24073e11355be3c4d2259066ae72912ba7367dfa204a9586e90fcf3/log.json --log-format json --systemd-cgr...
           ├─59816 /usr/bin/containerd-shim-runc-v2 -namespace moby -id 1dbc7c76fcad5369bb8aa2b54b810b9d96e80094f954b57eb711b061cc5f7e95 -address /run/containerd/containerd.sock
           ├─59819 runc init
           ├─59829 runc --root /var/run/docker/runtime-runc/moby --log /run/containerd/io.containerd.runtime.v2.task/moby/1dbc7c76fcad5369bb8aa2b54b810b9d96e80094f954b57eb711b061cc5f7e95/log.json --log-format json --systemd-cgr...
           ├─59837 runc init
           ├─59844 /usr/bin/containerd-shim-runc-v2 -namespace moby -id 0906327c85042a96fd86dece57ee87a4b9bafa6b19a6dc595159560a31b50d91 -address /run/containerd/containerd.sock
           ├─59870 /usr/bin/containerd-shim-runc-v2 -namespace moby -id 9d6b0f26a36539b9d1b20674d44834823b347fbb295466f73d1c17fd1238df66 -address /run/containerd/containerd.sock
           ├─59871 /usr/bin/containerd-shim-runc-v2 -namespace moby -id e829748e029a83aa491d03ac2e4a15c29d26bd7d0876991b5e63d7f222b91265 -address /run/containerd/containerd.sock
           ├─59872 runc --root /var/run/docker/runtime-runc/moby --log /run/containerd/io.containerd.runtime.v2.task/moby/0906327c85042a96fd86dece57ee87a4b9bafa6b19a6dc595159560a31b50d91/log.json --log-format json --systemd-cgr...
           ├─59886 runc --root /var/run/docker/runtime-runc/moby --log /run/containerd/io.containerd.runtime.v2.task/moby/e829748e029a83aa491d03ac2e4a15c29d26bd7d0876991b5e63d7f222b91265/log.json --log-format json --systemd-cgr...
           ├─59892 runc --root /var/run/docker/runtime-runc/moby --log /run/containerd/io.containerd.runtime.v2.task/moby/9d6b0f26a36539b9d1b20674d44834823b347fbb295466f73d1c17fd1238df66/log.json --log-format json --systemd-cgr...
           ├─59915 runc init
           ├─59918 /usr/bin/containerd-shim-runc-v2 -namespace moby -id 01edb2a032acb7b18800f114740b48cfa1f116a9206eb4cf3a019ceab4ad6f4d -address /run/containerd/containerd.sock
           ├─59920 runc init
           ├─59931 runc --root /var/run/docker/runtime-runc/moby --log /run/containerd/io.containerd.runtime.v2.task/moby/01edb2a032acb7b18800f114740b48cfa1f116a9206eb4cf3a019ceab4ad6f4d/log.json --log-format json --systemd-cgr...
           ├─59934 runc init
           ├─59954 /usr/bin/containerd-shim-runc-v2 -namespace moby -id 36b434eb461d0eef7daa15230d221b5088a7151ade305422e561df9909b76f34 -address /run/containerd/containerd.sock
           ├─59955 /usr/bin/containerd-shim-runc-v2 -namespace moby -id ad3f7ca66ab1dd7c2fc30c8f52423125846d3945ca762e7050c9e6970e4591cf -address /run/containerd/containerd.sock
           ├─59976 /usr/bin/containerd-shim-runc-v2 -namespace moby -id 3d9610fa2b7f24f5fa9068a2b2cab812aae2cda938f1ee6a6c331c3c8ddbb146 -address /run/containerd/containerd.sock
           ├─59979 runc --root /var/run/docker/runtime-runc/moby --log /run/containerd/io.containerd.runtime.v2.task/moby/ad3f7ca66ab1dd7c2fc30c8f52423125846d3945ca762e7050c9e6970e4591cf/log.json --log-format json --systemd-cgr...
           ├─59981 runc init
           ├─59988 runc --root /var/run/docker/runtime-runc/moby --log /run/containerd/io.containerd.runtime.v2.task/moby/36b434eb461d0eef7daa15230d221b5088a7151ade305422e561df9909b76f34/log.json --log-format json --systemd-cgr...
           ├─59993 runc --root /var/run/docker/runtime-runc/moby --log /run/containerd/io.containerd.runtime.v2.task/moby/3d9610fa2b7f24f5fa9068a2b2cab812aae2cda938f1ee6a6c331c3c8ddbb146/log.json --log-format json --systemd-cgr...
           ├─60011 runc init
           ├─60012 runc init
           └─60016 runc init

9月 17 11:08:17 k8s-master-node1 containerd[1099]: time="2021-09-17T11:08:17.717589947+08:00" level=info msg="starting signal loop" namespace=moby path=/run/containerd/io.containerd.runtime.v2.task/moby/11c20323...06f34 pid=13378
9月 17 11:08:17 k8s-master-node1 containerd[1099]: time="2021-09-17T11:08:17.790515162+08:00" level=info msg="starting signal loop" namespace=moby path=/run/containerd/io.containerd.runtime.v2.task/moby/88ba50bc...43187 pid=13519
9月 17 11:08:17 k8s-master-node1 containerd[1099]: time="2021-09-17T11:08:17.790429041+08:00" level=info msg="starting signal loop" namespace=moby path=/run/containerd/io.containerd.runtime.v2.task/moby/71815007...1e2db pid=13521
9月 17 11:08:18 k8s-master-node1 containerd[1099]: time="2021-09-17T11:08:18.079660246+08:00" level=info msg="starting signal loop" namespace=moby path=/run/containerd/io.containerd.runtime.v2.task/moby/1117e5ea...ac7f2 pid=13719
9月 17 11:08:18 k8s-master-node1 containerd[1099]: time="2021-09-17T11:08:18.115206852+08:00" level=info msg="starting signal loop" namespace=moby path=/run/containerd/io.containerd.runtime.v2.task/moby/415bc961...c3c97 pid=13745
9月 17 11:08:18 k8s-master-node1 containerd[1099]: time="2021-09-17T11:08:18.123705664+08:00" level=info msg="starting signal loop" namespace=moby path=/run/containerd/io.containerd.runtime.v2.task/moby/8bb82871...ed573 pid=13765
9月 17 11:08:18 k8s-master-node1 containerd[1099]: time="2021-09-17T11:08:18.135643930+08:00" level=info msg="starting signal loop" namespace=moby path=/run/containerd/io.containerd.runtime.v2.task/moby/6402bd99...60531 pid=13792
9月 17 11:08:18 k8s-master-node1 containerd[1099]: time="2021-09-17T11:08:18.135582481+08:00" level=info msg="starting signal loop" namespace=moby path=/run/containerd/io.containerd.runtime.v2.task/moby/796e3259...176d5 pid=13797
9月 17 11:08:18 k8s-master-node1 containerd[1099]: time="2021-09-17T11:08:18.167797951+08:00" level=info msg="starting signal loop" namespace=moby path=/run/containerd/io.containerd.runtime.v2.task/moby/fbda895d...1cafb pid=13827
9月 17 11:08:18 k8s-master-node1 containerd[1099]: time="2021-09-17T11:08:18.179913558+08:00" level=info msg="starting signal loop" namespace=moby path=/run/containerd/io.containerd.runtime.v2.task/moby/c5d2eb6d...3deb9 pid=13848
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by lework** [comment]
看信息，是内存不够用，导致pod驱逐了。
