### ISSUE TITLE
Wondering if you can create a WeChat group? Because QQ is basically useless

### ISSUE THREAD

**Issue by wl4g** [lework/kainstall#23]

**Comment by lework** [comment]
我建立了一个，欢迎加入。
![e22def94b014879db5b258d78a1f072](https://user-images.githubusercontent.com/17396943/155058195-e4ede0be-12ca-434e-b6bb-97b06debe0ad.jpg)

**Comment by wl4g** [comment]
二维码容易过期，如果方便的话可以发下微信号

**Comment by lework** [comment]
![8d7dae92b48f8470534e005217e55e7](https://user-images.githubusercontent.com/17396943/158298098-d477cc60-f928-4d1c-941f-4053a7967ce8.jpg)
过期后，在通知我下

**Comment by wl4g** [comment]
多谢
