### ISSUE TITLE
离线部署时，镜像coredns名字的问题

### ISSUE THREAD

**Issue by Kunple-w** [lework/kainstall#25]
离线文件版本: 1.23.1 centos7

好像coredns的镜像名字有些问题
执行完脚本load出来的名字是: `registry.cn-hangzhou.aliyuncs.com/kainstall/coredns:v1.8.6` 但是kubeadm实际使用的是
`registry.cn-hangzhou.aliyuncs.com/kainstall/coredns/coredns:v1.8.6`，在离线安装时会下载coredns

我的临时解决措施是在脚本执行过程中，重新tag为后者，就可以了

**Comment by lework** [comment]
嗯，这个是新版本更改coredns的镜像地址，我后面修复下。

**Comment by lework** [comment]
最新的版本已修复。https://github.com/lework/kainstall-offline/releases
