### ISSUE TITLE
kubeadm init failed错误

### ISSUE THREAD

**Issue by wenzhucjy** [lework/kainstall#3]
执行kainstall.sh init --master 192.168.2.52 --user root --password psd@123 --port 22 --version 1.19.7，提示kubeadm init failed，查看日志提示如下错误：
k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to watch *v1.Pod: failed to list *v1.Pod : Get "https://apiserver.cluster.local:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dk8s-master-node1&limit=500&resourceVersion=0": dial tcp 192.168.2.52:6443: connect: connection refused
请教下这个问题

**Comment by lework** [comment]
看这个错误，是连接不上apiserver，可以查看apiserver容器，主机网络：是否有防火墙设置。

**Comment by wenzhucjy** [comment]
> 看这个错误，是连接不上apiserver，可以查看apiserver容器，主机网络：是否有防火墙设置。

我检查了下防火墙是关闭的，lsof -i:6443端口不存在

**Comment by lework** [comment]
那就是apiserver启动有问题了，可以到qq群：467645743 我们即时沟通。

**Comment by lework** [comment]
此问题是因为slice未创建导致kublet 启动出错，已修复代码。
