### ISSUE TITLE
kubeadm init failed

### ISSUE THREAD

**Issue by jdAction** [lework/kainstall#35]
unknown configuration schema.GroupVersionKind{Group:"kubeadm.k8s.io", Version:"v1beta3", Kind:"InitConfiguration"} for scheme definitions in "k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/scheme/scheme.go:31" and "k8s.io/kubernetes/cmd/kubeadm/app/componentconfigs/scheme.go:28"
no kind "InitConfiguration" is registered for version "kubeadm.k8s.io/v1beta3" in scheme "k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/scheme/scheme.go:31"
To see the stack trace of this error execute with --v=5 or higher

如何修复
![image](https://user-images.githubusercontent.com/87454525/181046517-ec6cf6ad-cd0e-4757-9457-5f3a8e7ac705.png)

**Comment by lework** [comment]
这个是用新脚本安装了老版本的k8s版本了。

**Comment by jdAction** [comment]
谢谢指导
