### ISSUE TITLE
kube-flannel.yml里的镜像国内不好下

### ISSUE THREAD

**Issue by tiro8183** [lework/kainstall#44]
![image](https://user-images.githubusercontent.com/28704881/216800799-610ad7df-d1d9-429f-a8e0-715e9c6fa1ff.png)

**Comment by runzhenghengbin** [comment]
我昨天构建也是有问题

**Comment by lework** [comment]
我看里面用的是 docker.io/flannel/flannel:v0.21.2 仓库镜像，这个估计是阿里云代理那边限速了。

**Comment by ql4321** [comment]
[waiting] flannel pods ready failed.

**Comment by ql4321** [comment]
> [waiting] flannel pods ready failed.

这个问题是啥原因呢?
