### ISSUE TITLE
kainstall-ubuntu.sh uses deprecated parameter 'pod-eviction-timeout' in kube-controller-manager configuration, causing kubeadm init failure

### ISSUE THREAD

**Issue by littlepenguin3** [lework/kainstall#53]
Hello,

I have found an issue in the `kainstall-ubuntu.sh` script related to the configuration of kube-controller-manager. The script is currently using the deprecated parameter `pod-eviction-timeout`, which leads to an incorrect configuration file being generated by kubeadm, ultimately causing the kubeadm init process to fail.

To fix this issue, I suggest removing or commenting out the line with the `pod-eviction-timeout` parameter in the kube-controller-manager configuration:

```yaml
# pod-eviction-timeout: '2m' （the `pod-eviction-timeout` flag is deprecated for v1.26 and later versions ）

Please consider updating the script to address this issue, ensuring that it is compatible with newer Kubernetes versions.

Thank you for your attention to this matter.

**Comment by lework** [comment]
It has been removed, thank you
