### ISSUE TITLE
目前默认镜像仓库提供了什么版本的k8s呢？使用1.16.15版本没有镜像

### ISSUE THREAD

**Issue by clcc2019** [lework/kainstall#7]
[ERROR ImagePull]: failed to pull image registry.cn-hangzhou.aliyuncs.com/kainstall/etcd:3.3.15-0: output: Error response from daemon: manifest for registry.cn-hangzhou.aliyuncs.com/kainstall/etcd:3.3.15-0 not found: manifest unknown: manifest unknown

**Comment by lework** [comment]
没有提供`1.16.15`的镜像。

目前提供了以下版本

````
['v1.17.17', 'v1.18.15', 'v1.18.16', 'v1.18.17', 'v1.18.18','v1.18.19', 'v1.19.10', 'v1.19.11','v1.19.8', 'v1.19.9', 'v1.20.3', 'v1.20.4', 'v1.20.5', 'v1.20.6', 'v1.20.7', 'v1.21.0', 'v1.21.1']
```

由 https://github.com/lework/sync_image 项目支持。
