### ISSUE TITLE
1.21.1版本离线安装pause版本不对

### ISSUE THREAD

**Issue by WangJinglin** [lework/kainstall#8]
离线包中的pause版本是3.4.1，kainstall-centos.sh中的是3.2。
离线安装时kubesphere也需要在线下载导致安装失败

bash kainstall-centos.sh init \
  --master 10.30.44.110,10.30.44.111,10.30.44.112 \
  --worker 10.30.44.113,10.30.44.114 \
  --user root \
  --password 123456 \
  --version 1.21.1 \
  --ui kubesphere \
  --offline-file 1.21.1_centos7.tgz

**Comment by lework** [comment]
在 1.21.x 版本后，pause 版本变更到3.4.1了。目前 pause 版本问题我修复了。
离线包只包含了kainstall 默认参数所需要的安装包。
安装 kubesphere，还需要一个 storage 组件。
